#!/bin/bash
# install.sh — set up claude-telegram-autostart on this Mac.
# - generates ~/.config/claude-telegram-autostart/config.env
# - copies start script to ~/.local/bin/
# - renders LaunchAgent plist into ~/Library/LaunchAgents/
# - loads the agent via launchctl bootstrap

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DRY_RUN=0
NO_LOAD=0
NON_INTERACTIVE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --no-load) NO_LOAD=1 ;;
    --yes|-y)  NON_INTERACTIVE=1 ;;
    --help|-h)
      cat <<EOF
Usage: $0 [--dry-run] [--no-load] [--yes]

Installs claude-telegram-autostart on this Mac.

Flags:
  --dry-run      Print actions, change nothing
  --no-load      Skip 'launchctl bootstrap' (install files only)
  --yes, -y      Non-interactive (use defaults / env vars)
  --help, -h     Show this help

Override via env (also picked up in non-interactive mode):
  PROJECT_DIR=...   Working directory for the claude session
EOF
      exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
  shift
done

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!!\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31mxxx\033[0m %s\n' "$*" >&2; exit 1; }

run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    printf '[dry-run]'
    printf ' %q' "$@"
    printf '\n'
  else
    "$@"
  fi
}

[ "$(uname)" = "Darwin" ] || fail "macOS only (LaunchAgents)."

TMUX_BIN="$(command -v tmux || true)"
CLAUDE_BIN="$(command -v claude || true)"
[ -n "$TMUX_BIN" ]   || fail "tmux not found in PATH. Install: brew install tmux"
[ -n "$CLAUDE_BIN" ] || fail "claude not found in PATH. Install Claude Code first."

info "tmux:   $TMUX_BIN"
info "claude: $CLAUDE_BIN"

if [ -z "${PROJECT_DIR:-}" ]; then
  if [ "$NON_INTERACTIVE" -eq 1 ]; then
    PROJECT_DIR="$HOME"
  else
    printf 'Working directory for the claude session [%s]: ' "$HOME"
    read -r answer || true
    PROJECT_DIR="${answer:-$HOME}"
  fi
fi
PROJECT_DIR="${PROJECT_DIR/#\~/$HOME}"
[ -d "$PROJECT_DIR" ] || fail "PROJECT_DIR does not exist: $PROJECT_DIR"
info "project dir: $PROJECT_DIR"

USER_NAME="$(id -un)"
LABEL="com.${USER_NAME}.claude-telegram"
WATCHDOG_LABEL="com.${USER_NAME}.claude-telegram-watchdog"
LOCAL_BIN="$HOME/.local/bin"
SCRIPT_DST="$LOCAL_BIN/start-claude-telegram.sh"
WATCHDOG_DST="$LOCAL_BIN/claude-telegram-watchdog.sh"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/claude-telegram-autostart"
CONFIG_DST="$CONFIG_DIR/config.env"
LAUNCHAGENTS_DIR="$HOME/Library/LaunchAgents"
PLIST_DST="$LAUNCHAGENTS_DIR/${LABEL}.plist"
WATCHDOG_PLIST_DST="$LAUNCHAGENTS_DIR/${WATCHDOG_LABEL}.plist"
LOGS_DIR="$HOME/Library/Logs"
LAUNCH_PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.local/bin"

info "label:    $LABEL"
info "watchdog: $WATCHDOG_LABEL"

run mkdir -p "$LOCAL_BIN" "$CONFIG_DIR" "$LAUNCHAGENTS_DIR" "$LOGS_DIR"

if [ -f "$CONFIG_DST" ]; then
  warn "config already exists, leaving as-is: $CONFIG_DST"
else
  info "writing $CONFIG_DST"
  if [ "$DRY_RUN" -eq 0 ]; then
    cat > "$CONFIG_DST" <<EOF
# claude-telegram-autostart configuration
# Generated by install.sh on $(date '+%Y-%m-%d')

PROJECT_DIR="$PROJECT_DIR"
TMUX_SESSION="claude-tg"
TMUX_BIN="$TMUX_BIN"
CLAUDE_BIN="$CLAUDE_BIN"
CHANNELS_SPEC="plugin:telegram@claude-plugins-official"
DIALOG_TIMEOUT=30
LOG_FILE="\$HOME/Library/Logs/claude-telegram.log"
EOF
  fi
fi

install_script() {
  local src="$1" dst="$2"
  [ -f "$src" ] || fail "Missing source: $src"
  if [ -f "$dst" ] && ! diff -q "$src" "$dst" >/dev/null 2>&1; then
    if [ "$NON_INTERACTIVE" -eq 0 ]; then
      warn "Script at $dst differs from repo version. Overwrite? [y/N]"
      read -r answer || true
      case "$answer" in
        y|Y|yes) ;;
        *) fail "Aborted by user." ;;
      esac
    fi
  fi
  info "installing script → $dst"
  run cp "$src" "$dst"
  run chmod +x "$dst"
}

render_plist() {
  local src="$1" dst="$2" label="$3" script="$4"
  [ -f "$src" ] || fail "Missing template: $src"
  info "rendering plist → $dst"
  if [ "$DRY_RUN" -eq 0 ]; then
    sed \
      -e "s|__LABEL__|$label|g" \
      -e "s|__SCRIPT__|$script|g" \
      -e "s|__HOME__|$HOME|g" \
      -e "s|__PATH__|$LAUNCH_PATH|g" \
      "$src" > "$dst"
    plutil -lint "$dst" >/dev/null || fail "plutil rejected $dst"
  fi
}

load_agent() {
  local label="$1" plist="$2"
  info "loading LaunchAgent ($label)"
  if [ "$DRY_RUN" -eq 0 ]; then
    launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
    if ! launchctl bootstrap "gui/$(id -u)" "$plist" 2>/dev/null; then
      warn "bootstrap failed for $label, falling back to legacy 'launchctl load'"
      launchctl load "$plist"
    fi
  fi
}

install_script "$SCRIPT_DIR/bin/start-claude-telegram.sh" "$SCRIPT_DST"
install_script "$SCRIPT_DIR/bin/watchdog.sh" "$WATCHDOG_DST"

render_plist "$SCRIPT_DIR/launchd/com.user.claude-telegram.plist.template" \
  "$PLIST_DST" "$LABEL" "$SCRIPT_DST"
render_plist "$SCRIPT_DIR/launchd/com.user.claude-telegram-watchdog.plist.template" \
  "$WATCHDOG_PLIST_DST" "$WATCHDOG_LABEL" "$WATCHDOG_DST"

if [ "$NO_LOAD" -eq 1 ]; then
  warn "skipping launchctl (--no-load)"
else
  load_agent "$LABEL" "$PLIST_DST"
  load_agent "$WATCHDOG_LABEL" "$WATCHDOG_PLIST_DST"
fi

cat <<EOF

✅ Installed.

  Script:               $SCRIPT_DST
  Watchdog:             $WATCHDOG_DST
  Config:               $CONFIG_DST
  LaunchAgent:          $PLIST_DST
  Watchdog LaunchAgent: $WATCHDOG_PLIST_DST
  Logs:                 $LOGS_DIR/claude-telegram*.log

To test now (will pop the confirmation dialog):
  $SCRIPT_DST

To attach to the running session:
  tmux attach -t claude-tg

The watchdog runs every 60s in the background. Logs:
  tail -f $LOGS_DIR/claude-telegram-watchdog.log

To uninstall:
  $SCRIPT_DIR/uninstall.sh
EOF
